<a href="https://colab.research.google.com/github/awaaat/CodeMaster/blob/main/00_pytorch_machie_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello World, I am now officially starting my Machine learning journey. Till I am an expert, May God alwways be with me. ")

Hello World, I am now officially starting my Machine learning journey. Till I am an expert, May God alwways be with me. 


In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torchvision
print(torch.__version__)


2.1.0+cu121


#We Start with introduction to Tensors
Creating Tensors

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

#Vector

In [12]:
vector  = torch.tensor([2,5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([2, 5])
1
torch.Size([2])


#Matrix

In [24]:
matrix = torch.tensor([[7, 8, 6], [9, 10, 2], [5, 10, 11]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8,  6],
        [ 9, 10,  2],
        [ 5, 10, 11]])
2
torch.Size([3, 3])


In [18]:
matrix[0]

tensor([7, 8])

#Tensor

In [21]:
Tensor = torch.tensor([[1,2,5], [4,5,6,], [7,8,9], [10, 11, 12]])
print(Tensor, Tensor.ndim, Tensor.shape)

tensor([[ 1,  2,  5],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 2 torch.Size([4, 3])


#Random tensors
##They are important because machines start with generating random numbers and then finding somethng close to teh pattern of the required output.

In [27]:
Rand_Tensor = torch.rand(4, 6)
print(Rand_Tensor)
rand_zero = torch.zeros(3,5)
print(rand_zero)

tensor([[0.1612, 0.7599, 0.0341, 0.1186, 0.5756, 0.2928],
        [0.6532, 0.3283, 0.8069, 0.6048, 0.9877, 0.2599],
        [0.7553, 0.7889, 0.6704, 0.5800, 0.7286, 0.7738],
        [0.2869, 0.4637, 0.9024, 0.6891, 0.7024, 0.4655]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [30]:
tensor_ones = torch.ones(size = (3, 5))
print(tensor_ones)
tensor_ones.dtype

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


torch.float32

In [5]:
import torch
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
float_32_tensor = torch.tensor([5,7,0], dtype = torch.float32)

(int_32_tensor * float_32_tensor).dtype


torch.float32

#Tensor Multiplicaton

In [17]:
import torch
tensor_A = torch.tensor([[1,2],
                        [4,5],
                        [7,8]])
tensor_B = torch.tensor([[9, 10, 11],
                        [12, 11, 14],
                        [14, 15, 16]])
print(torch.matmul(tensor_A.T, tensor_B))
print(tensor_A.shape, tensor_B.shape)

tensor([[155, 159, 179],
        [190, 195, 220]])
torch.Size([3, 2]) torch.Size([3, 3])


#Tensor Agreggations


In [43]:
x = torch.arange(0, 1000, 5)
x
print(x.dtype)
print( x.min())
print(+ x.max())
print(torch.mean(x.type(torch.float32))) #This is how to find mean. We must have the right datatype. (Tensor of float32)
print(sum(x))
print(x.argmax())
print(x.argmin())


torch.int64
tensor(0)
tensor(995)
tensor(497.5000)
tensor(99500)
tensor(199)
tensor(0)


#Pytorch Torch And Numpy

In [47]:
import torch
import numpy as np
np_array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(np_array)
np_array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
import torch
torch.cuda.is_available()


True

In [51]:
device = "cuda" if torch.cuda.is_available() else cpu
print(device)

cuda
